# Generated by Django 5.1.4 on 2025-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_name', models.CharField(max_length=20)),
                ('test_field_int', models.IntegerField(max_length=10)),
            ],
        ),
    ]
