# Generated by Django 5.2.1 on 2025-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmodel",
            name="test_field_int",
            field=models.IntegerField(),
        ),
    ]
