# Generated by Django 5.2.1 on 2025-06-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_warehouse_users"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productstock",
            unique_together=set(),
        ),
    ]
